name: urna
description: "Uma urna de votação para representantes de sala."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  file_picker: ^10.3.8
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1
  flutter_svg: ^2.2.3
  go_router: ^17.0.0
  google_fonts: ^6.3.2
  hooks_riverpod: ^3.1.0
  path: ^1.9.1
  path_provider: ^2.1.5
  riverpod_annotation: ^4.0.0
  sizer: ^3.1.3
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.6
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.7
  riverpod_generator: ^4.0.0+1
  build_runner: ^2.7.1

flutter:
  uses-material-design: true
